pipeline {
    agent { 
        label 'master' 
    }
    tools {
        maven 'maven'
        jdk 'JAVA_HOME'
    }
	options {
        skipDefaultCheckout() 
    }
    stages {
        stage("Checkout SCM") {
            steps {
			    cleanWs()
			    echo 'checkout scm'
			    checkout scm
		    }
	    }
        			
		stage('Build and Package (with code quality check)') {
			steps {
				echo 'Clean Build'
				sh "ls"
				sh "pwd"
				sh "mvn clean compile package -Dtest=\\!TestRunner* -DfailIfNoTests=false"
                archiveArtifacts artifacts: 'target/*.war'
			}
		}
		
		stage('Spin new Developer QA Environment with Tomcat 8') {
			steps {
                sh ''' cd Jobs/Provision-qa
                terraform init
                terraform plan
                terraform apply --auto-approve
                terraform output
                terraform output.server-public-ip
                '''
                //String cmd = ("terraform output")
                //env.server-ip = sh(script: cmd, returnStdout: true)
                //echo $env.server-ip
                sh '''touch server-ip.txt'
                env.serverIP=$(terraform output)
                '''
                sh 'terraform output > server-ip.txt'
			}
		}

        stage('Deploy war file to tomcat container') {
            steps {
                echo 'copy file to container'
                //sh 'terraform output server-public-ip'
                //def fileContent = sh(returnStdout: true, script: "terraform output server-public-ip")
                //writeFile file: "${WORKSPACE}/server-ip.txt", text: fileContent
                //sh 'terraform output server-public-ip > server-ip.txt'
                sh "cat ${WORKSPACE}/server-ip.txt"
                //String server_ip = sh 'terraform output server-public-ip'
                //sh 'export ip_address="$(cat ${WORKSPACE}/server-ip.txt)"'
                echo $env.serverIP
                sh 'ssh ubuntu@$env.serverIP'
                sh 'scp target/*.war $env.serverIP:/var/lib/tomcat9/webapps/'
            }
        }
    }
    post {
        always {
            echo 'JENKINS PIPELINE'
        }
        success {
            echo 'JENKINS PIPELINE SUCCESSFUL'
        }
        failure {
            echo 'JENKINS PIPELINE FAILED'
        }
        unstable {
            echo 'JENKINS PIPELINE WAS MARKED AS UNSTABLE'
        }
        changed {
            echo 'JENKINS PIPELINE STATUS HAS CHANGED SINCE LAST EXECUTION'
        }
    }
}
