# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ DEV ]
    paths-ignore:
      - 'kube/*'
  pull_request:
    branches: [ DEV ]
    paths-ignore:
      - 'kube/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: CodeQualityCheck
        run: mvn sonar:sonar -Dsonar.projectKey=addressBook -Dsonar.host.url=${{ secrets.DEV_SONARQUBEURL }} -Dsonar.login=${{ secrets.DEV_SONARQUBETOKEN }}
      - name: Run Insider (SAST)
        uses: insidersec/insider-action@v0
        with:
            technology: javascript
            # Relative path under $GITHUB_WORKSPACE to use as a target
            # In this example, will use $GITHUB_WORKSPACE/src as a target
            target: src
      - name: Unit Test
        run: mvn test --file pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}        
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rakesh635/addressbook:dev${{ steps.buildnumber.outputs.build_number }}

